name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Lint and static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'sdk'
      - name: Checkout depot_tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Add depot_tools to path
        run: echo $(realpath depot_tools) >> $GITHUB_PATH
#      - name: Set origin
#        working-directory: ./sdk
#        run: git branch -u origin/main
#fatal: could not set upstream of HEAD to origin/main when it does not point to any branch.
#Error: Process completed with exit code 128.
      - name: Run presubmit
        working-directory: ./sdk
        run: git cl presubmit
